version: '3.8'
services:
  db:
    build:
      context: ./migrations
      dockerfile: pg-Dockerfile
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  app:
    build: .
    restart: always
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/redex
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      - db
    ports:
      - "8080:8080"